on:
    workflow_dispatch:
    push:
      branches: ["master"]
    pull_request:
      branches: ["master"]
jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    - run: dotnet restore
    - run: dotnet build --no-restore --configuration Debug
    - run: dotnet test --no-build --configuration Debug
    # - name: Get Allure history
    #   uses: actions/checkout@v4
    #   if: always()
    #   continue-on-error: true
    #   with:
    #     ref: gh-pages
    #     path: gh-pages
    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        allure_history: allure-history
        allure_results: src/allure-results
    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
                
